# Generated by Django 4.2.30 on 2026-06-14 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitly', '0003_auditlog_csvimport_currency_expenseparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ai_suggested_category',
            field=models.CharField(blank=True, help_text='Category suggested by AI extraction engine', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='imported_from_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importlog',
            name='source',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], default='csv', max_length=5),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('expense_added', 'Expense Added'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('settlement_added', 'Settlement Added'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('csv_imported', 'CSV Imported'), ('pdf_imported', 'PDF Imported'), ('pdf_generated', 'PDF Generated')], max_length=30),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='splitly.csvimport'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('expense_added', 'Expense Added'), ('settlement_completed', 'Settlement Completed'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('csv_imported', 'CSV Imported'), ('pdf_imported', 'PDF Imported'), ('report_generated', 'Report Generated')], max_length=30),
        ),
        migrations.CreateModel(
            name='PDFImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf_imports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('extracted_text', models.TextField(blank=True, help_text='Full text extracted from PDF')),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_imports', to='splitly.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='importlog',
            name='pdf_import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_rows', to='splitly.pdfimport'),
        ),
    ]
